parameters:
    LIST_DISPLAY_LIMIT: 10
    LIST_DISPLAY_PAGE_RANGE: 5

services:
    category_manager_interface:
        class: Atw\TestBundle\Service\Category\CategoryManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @validator
