parameters:
    LIST_DISPLAY_LIMIT: 10
    LIST_DISPLAY_PAGE_RANGE: 5

services:
    category_manager_interface:
        class: Atw\TestBundle\Service\Category\CategoryManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @validator

    article_manager_interface:
        class: Atw\TestBundle\Service\Article\ArticleManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @validator

    datetime_format_extension:
        class: Atw\TestBundle\Twig\DateTimeFormatExtension
        tags:
            - { name: twig.extension }

    get_category_list_extension:
        class: Atw\TestBundle\Twig\GetCategoryListExtension
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: twig.extension }

